# Ejercicio


Fase 1: Exploración y Limpieza

. Exploración Inicial:
- Realiza una exploración inicial de los datos para identificar posibles problemas, como valores nulos, atípicos o datos faltantes en las columnas relevantes --> head, tail, sample, info
- Utiliza funciones de Pandas para obtener información sobre la estructura de los datos, la presencia de valores nulos y estadísticas básicas de las columnas involucradas.
- Une los dos conjuntos de datos de la forma más eficiente.

. Limpieza de Datos:
- Elimina o trata los valores nulos, si los hay, en las columnas clave para asegurar que los datos estén completos.
- Verifica la consistencia y corrección de los datos para asegurarte de que los datos se presenten de forma coherente.
- Realiza cualquier ajuste o conversión necesaria en las columnas (por ejemplo, cambiar tipos de datos) para garantizar la adecuación de los datos para el análisis estadístico

In [1]:
import pandas as pd
import numpy as numpy
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Realiza una exploración inicial de los datos para identificar posibles problemas, como valores nulos, atípicos o datos faltantes en las columnas relevantes.

def exploracion_inicial(df):
    display(df.head(2))
    print("=" * 100)
    display(df.tail(2))
    print("=" * 100)
    display(df.sample(2))
    print("=" * 100)
    print(df.info())
    print("=" * 100)
    print(" " * 100)
    print(f"El dataframe history tiene {df.shape[0]} filas y {df.shape[1]} columnas")

In [3]:
# DataFrame 1 

df_history = pd.read_csv("Customer_Loyalty_History.csv")

exploracion_inicial(df_history)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
1201,915638,Canada,Quebec,Tremblant,H5Y 2S9,Male,Bachelor,63116.0,Married,Aurora,5461.97,Standard,2016,11,NaN,NaN
5541,874612,Canada,Saskatchewan,Regina,S6J 3G0,Female,Bachelor,68160.0,Single,Nova,3969.43,Standard,2012,10,NaN,NaN

====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB
None
====================================================================================================

El dataframe history tiene 16737 filas y 16 columnas

In [4]:
# DataFrame 2

df_activity = pd.read_csv("Customer_flight_activity.csv")

exploracion_inicial(df_activity)

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

====================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
383981,956081,2017,10,0,0,0,0,0.0,0,0
321548,123083,2018,8,7,6,13,4082,408.0,0,0

====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB
None
====================================================================================================

El dataframe history tiene 405624 filas y 10 columnas

LIMPIEZA

1. Nombre se las columnas en minuscula, separar palabras con _ y guardar

2. Conversion tipos de dato:
df_history: Salary a int
df_history: cancellation month y year a int
df_activity: points redeemed a float como points accumulated

3. Eliminar duplicados

4. gestionar nulos: df_history: salary, cancellation year y month

5. gestion numeros negativos en salary

6. guardar df limpios + nuevo df unido

In [5]:
# añadir _ a los nombres de las columnas y poner en minúscula
# 1. ver las columnas

df_history.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='object')

In [6]:
# 2. añadir _ y poner en minúscula

col_nuevas_history = {col: col.lower().replace(" ", "_") for col in df_history.columns}   

col_nuevas_history

{'Loyalty Number': 'loyalty_number',
 'Country': 'country',
 'Province': 'province',
 'City': 'city',
 'Postal Code': 'postal_code',
 'Gender': 'gender',
 'Education': 'education',
 'Salary': 'salary',
 'Marital Status': 'marital_status',
 'Loyalty Card': 'loyalty_card',
 'CLV': 'clv',
 'Enrollment Type': 'enrollment_type',
 'Enrollment Year': 'enrollment_year',
 'Enrollment Month': 'enrollment_month',
 'Cancellation Year': 'cancellation_year',
 'Cancellation Month': 'cancellation_month'}

In [7]:
# comprobando. al hacer esto, el df original sigue siendo como era

df_history

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,NaN,Married,Star,61850.19,Standard,2012,12,NaN,NaN
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.0,Married,Star,67907.27,Standard,2014,9,NaN,NaN
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014,3,NaN,NaN
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

In [8]:
# para aplicar los cambios:

df_history.rename(columns= col_nuevas_history, inplace=True)

df_history.head(2)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

In [9]:
df_activity.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='object')

In [10]:
col_nuevas_activity = {col: col.lower().replace(" ", "_") for col in df_activity.columns}   

col_nuevas_activity

{'Loyalty Number': 'loyalty_number',
 'Year': 'year',
 'Month': 'month',
 'Flights Booked': 'flights_booked',
 'Flights with Companions': 'flights_with_companions',
 'Total Flights': 'total_flights',
 'Distance': 'distance',
 'Points Accumulated': 'points_accumulated',
 'Points Redeemed': 'points_redeemed',
 'Dollar Cost Points Redeemed': 'dollar_cost_points_redeemed'}

In [11]:
df_activity.rename(columns= col_nuevas_activity, inplace=True)

df_activity.head(2)

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

In [12]:
columnas_a_entero = ['salary', 'cancellation_month', 'cancellation_year']

for col in columnas_a_entero:
    df_history[col] = df_history[col].astype('Int64')

df_history[columnas_a_entero].dtypes

salary                Int64
cancellation_month    Int64
cancellation_year     Int64
dtype: object

In [13]:
df_history.sample(2)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
169,553936,Canada,Ontario,Toronto,P1J 8T7,Female,Bachelor,53465,Single,Star,4170.69,Standard,2014,12,2015,8
11302,471523,Canada,Ontario,Toronto,M1R 4K3,Male,College,<NA>,Single,Star,2611.84,Standard,2015,12,<NA>,<NA>

In [14]:
df_activity.columns

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed'],
      dtype='object')

In [15]:
columnas_a_float = ['points_redeemed']

for col in columnas_a_float:
    df_activity[col] = df_activity[col].astype('float64')

df_activity[columnas_a_float].dtypes

points_redeemed    float64
dtype: object

In [16]:
# comprobacion 1
df_activity.sample(2)

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
28972,741422,2017,2,2,0,2,466,46.0,0.0,0
208582,554888,2018,3,0,0,0,0,0.0,0.0,0

In [17]:
# comprobacion 2
df_history.dtypes

loyalty_number          int64
country                object
province               object
city                   object
postal_code            object
gender                 object
education              object
salary                  Int64
marital_status         object
loyalty_card           object
clv                   float64
enrollment_type        object
enrollment_year         int64
enrollment_month        int64
cancellation_year       Int64
cancellation_month      Int64
dtype: object

In [18]:
# comprobacion 3
df_activity.dtypes

loyalty_number                   int64
year                             int64
month                            int64
flights_booked                   int64
flights_with_companions          int64
total_flights                    int64
distance                         int64
points_accumulated             float64
points_redeemed                float64
dollar_cost_points_redeemed      int64
dtype: object

In [19]:
# comprobacion 4
df_history

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236,Married,Star,3839.14,Standard,2016,2,<NA>,<NA>
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,<NA>,Divorced,Star,3839.61,Standard,2016,3,<NA>,<NA>
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,<NA>,Single,Star,3839.75,Standard,2014,7,2018,1
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,<NA>,Single,Star,3839.75,Standard,2013,2,<NA>,<NA>
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495,Married,Star,3842.79,Standard,2014,10,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16732,823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,<NA>,Married,Star,61850.19,Standard,2012,12,<NA>,<NA>
16733,680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210,Married,Star,67907.27,Standard,2014,9,<NA>,<NA>
16734,776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,<NA>,Single,Star,74228.52,Standard,2014,3,<NA>,<NA>
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297,Married,Star,10018.66,2018 Promotion,2018,4,<NA>,<NA>
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049,Married,Star,83325.38,Standard,2015,12,2016,8

In [20]:
# comprobacion 5
df_activity

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152.0,0.0,0
1,100102,2017,1,10,4,14,2030,203.0,0.0,0
2,100140,2017,1,6,0,6,1200,120.0,0.0,0
3,100214,2017,1,0,0,0,0,0.0,0.0,0
4,100272,2017,1,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
405619,999902,2018,12,0,0,0,0,0.0,0.0,0
405620,999911,2018,12,0,0,0,0,0.0,0.0,0
405621,999940,2018,12,3,0,3,1233,123.0,0.0,0
405622,999982,2018,12,0,0,0,0,0.0,0.0,0
405623,999986,2018,12,0,0,0,0,0.0,0.0,0

In [21]:
# history
# numericas

df_history.describe(include= "number").T

,count,mean,std,min,25%,50%,75%,max
loyalty_number,16737.0,549735.880445,258912.132453,100018.0,326603.0,550434.0,772019.0,999986.0
salary,12499.0,79245.609409,35008.297285,-58486.0,59246.5,73455.0,88517.5,407228.0
clv,16737.0,7988.896536,6860.98228,1898.01,3980.84,5780.18,8940.58,83325.38
enrollment_year,16737.0,2015.253211,1.979111,2012.0,2014.0,2015.0,2017.0,2018.0
enrollment_month,16737.0,6.669116,3.398958,1.0,4.0,7.0,10.0,12.0
cancellation_year,2067.0,2016.503145,1.380743,2013.0,2016.0,2017.0,2018.0,2018.0
cancellation_month,2067.0,6.962748,3.455297,1.0,4.0,7.0,10.0,12.0

In [22]:
# history
# categoricas

df_history.describe(include="object").T

                 count unique       top   freq
country          16737      1    Canada  16737
province         16737     11   Ontario   5404
city             16737     29   Toronto   3351
postal_code      16737     55   V6E 3D9    911
gender           16737      2    Female   8410
education        16737      5  Bachelor  10475
marital_status   16737      3   Married   9735
loyalty_card     16737      3      Star   7637
enrollment_type  16737      2  Standard  15766

In [23]:
col_cat_history = df_history.select_dtypes(include="object").columns

col_cat_history

Index(['country', 'province', 'city', 'postal_code', 'gender', 'education',
       'marital_status', 'loyalty_card', 'enrollment_type'],
      dtype='object')

In [24]:
# recorrer cada columna para ver cuales son sus categorías

for col in col_cat_history:
    print(f"Categorias columna ¨{col}")
    print(df_history[col].unique())
    print("=" * 100)

Categorias columna ¨country
['Canada']
====================================================================================================
Categorias columna ¨province
['Ontario' 'Alberta' 'British Columbia' 'Quebec' 'Yukon' 'New Brunswick'
 'Manitoba' 'Nova Scotia' 'Saskatchewan' 'Newfoundland'
 'Prince Edward Island']
====================================================================================================
Categorias columna ¨city
['Toronto' 'Edmonton' 'Vancouver' 'Hull' 'Whitehorse' 'Trenton' 'Montreal'
 'Dawson Creek' 'Quebec City' 'Fredericton' 'Ottawa' 'Tremblant' 'Calgary'
 'Thunder Bay' 'Whistler' 'Peace River' 'Winnipeg' 'Sudbury'
 'West Vancouver' 'Halifax' 'London' 'Regina' 'Kelowna' "St. John's"
 'Victoria' 'Kingston' 'Banff' 'Moncton' 'Charlottetown']
====================================================================================================
Categorias columna ¨postal_code
['M2Z 4K1' 'T3G 6Y6' 'V6E 3D9' 'P1W 1K4' 'J8Y 3Z5' 'Y2K 6R0' 'P5S 6R4'
 'K8V 4B2' 'H2Y 2W2' 'M8Y 4K8' 'U5I 4F1' 'G1B 3L5' 'H4G 3T4' 'M2M 7K8'
 'M2M 6J7' 'E3B 2H2' 'M1R 4K3' 'T9G 1W3' 'H2Y 4R4' 'V5R 1W3' 'P1L 8X8'
 'K1F 2R2' 'H5Y 2S9' 'V1E 4R6' 'H2T 2J6' 'T3E 2V9' 'H2T 9K8' 'K8T 5M5'
 'V6T 1Y8' 'P2T 6G3' 'T9O 2W2' 'V6E 3Z3' 'R6Y 4T5' 'M5V 1G5' 'V6V 8Z3'
 'B3J 9S2' 'M5B 3E4' 'R2C 0M5' 'S6J 3G0' 'M2P 4F6' 'P1J 8T7' 'V09 2E9'
 'A1C 6H9' 'V10 6T5' 'B3C 2M8' 'M9K 2P4' 'T4V 1D4' 'R3R 3T4' 'S1J 3C5'
 'E1A 2A7' 'K1G 4Z0' 'H3T 8L4' 'C1A 6E8' 'H3J 5I6' 'M3R 4K8']
====================================================================================================
Categorias columna ¨gender
['Female' 'Male']
====================================================================================================
Categorias columna ¨education
['Bachelor' 'College' 'Master' 'High School or Below' 'Doctor']
====================================================================================================
Categorias columna ¨marital_status
['Married' 'Divorced' 'Single']
====================================================================================================
Categorias columna ¨loyalty_card
['Star' 'Aurora' 'Nova']
====================================================================================================
Categorias columna ¨enrollment_type
['Standard' '2018 Promotion']
====================================================================================================

In [25]:
# activity
# numericas (no tiene categóricas)

df_activity.describe(include= "number").T

,count,mean,std,min,25%,50%,75%,max
loyalty_number,405624.0,550037.873084,258935.286969,100018.0,326961.00,550834.0,772194.00,999986.0
year,405624.0,2017.500000,0.500001,2017.0,2017.00,2017.5,2018.00,2018.0
month,405624.0,6.500000,3.452057,1.0,3.75,6.5,9.25,12.0
flights_booked,405624.0,4.115052,5.225518,0.0,0.00,1.0,8.00,21.0
flights_with_companions,405624.0,1.031805,2.076869,0.0,0.00,0.0,1.00,11.0
total_flights,405624.0,5.146858,6.521227,0.0,0.00,1.0,10.00,32.0
distance,405624.0,1208.880059,1433.155320,0.0,0.00,488.0,2336.00,6293.0
points_accumulated,405624.0,123.692721,146.599831,0.0,0.00,50.0,239.00,676.5
points_redeemed,405624.0,30.696872,125.486049,0.0,0.00,0.0,0.00,876.0
dollar_cost_points_redeemed,405624.0,2.484503,10.150038,0.0,0.00,0.0,0.00,71.0

In [26]:
# duplicados

print(df_history.duplicated().sum())

0

In [27]:
print(df_activity.duplicated().sum())

1864

In [28]:
# ver que está duplicado

mascara_duplicados_activity = df_activity.duplicated(keep=False)
mascara_duplicados_activity

0         False
1         False
2         False
3         False
4         False
          ...
405619    False
405620    False
405621    False
405622    False
405623    False
Length: 405624, dtype: bool

In [29]:
df_activity[mascara_duplicados_activity].sort_values(by="loyalty_number")

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
185953,101902,2017,12,0,0,0,0,0.0,0.0,0
185952,101902,2017,12,0,0,0,0,0.0,0.0,0
101447,101902,2017,7,0,0,0,0,0.0,0.0,0
101448,101902,2017,7,0,0,0,0,0.0,0.0,0
33844,101902,2017,3,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
151971,992168,2017,9,0,0,0,0,0.0,0.0,0
101268,992168,2017,6,0,0,0,0,0.0,0.0,0
354784,992168,2018,9,0,0,0,0,0.0,0.0,0
304080,992168,2018,6,0,0,0,0,0.0,0.0,0
304081,992168,2018,6,0,0,0,0,0.0,0.0,0

In [30]:
df_activity.drop_duplicates(inplace=True)
print(df_activity.duplicated().sum())

0

In [31]:
# Nulos. solo hay en numéricas y en history

In [32]:
print(df_history.isnull().sum())

loyalty_number            0
country                   0
province                  0
city                      0
postal_code               0
gender                    0
education                 0
salary                 4238
marital_status            0
loyalty_card              0
clv                       0
enrollment_type           0
enrollment_year           0
enrollment_month          0
cancellation_year     14670
cancellation_month    14670
dtype: int64

In [33]:
nulos_history = ((df_history.select_dtypes(include="number").isnull().sum() / df_history.shape[0]) * 100)

nulos_history = nulos_history.reset_index()

nulos_history.rename(columns={"index": "nombre_columna", 0: "%_nulos"}, inplace=True)

nulos_history

       nombre_columna    %_nulos
0      loyalty_number   0.000000
1              salary  25.321145
2                 clv   0.000000
3     enrollment_year   0.000000
4    enrollment_month   0.000000
5   cancellation_year  87.650117
6  cancellation_month  87.650117

Al tener tantos nulos tenemos que utilizar opciones avanzadas. Antes de seguir con los nulos voy a ver que pasa con los negativos

In [34]:
# comprobar 

print(df_history.isnull().sum())

loyalty_number            0
country                   0
province                  0
city                      0
postal_code               0
gender                    0
education                 0
salary                 4238
marital_status            0
loyalty_card              0
clv                       0
enrollment_type           0
enrollment_year           0
enrollment_month          0
cancellation_year     14670
cancellation_month    14670
dtype: int64

In [35]:
#buscar los salarios negativos

df_history[df_history['salary'] < 0]

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
1082,542976,Canada,Quebec,Montreal,H2Y 4R4,Male,High School or Below,-49830,Divorced,Star,24127.50,2018 Promotion,2018,3,<NA>,<NA>
1894,959977,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,-12497,Married,Aurora,9453.00,2018 Promotion,2018,3,<NA>,<NA>
2471,232755,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,-46683,Single,Nova,4787.81,2018 Promotion,2018,3,<NA>,<NA>
3575,525245,Canada,British Columbia,Victoria,V10 6T5,Male,Bachelor,-45962,Married,Star,2402.33,2018 Promotion,2018,3,<NA>,<NA>
3932,603070,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,-19325,Single,Star,2893.74,2018 Promotion,2018,3,<NA>,<NA>
4712,491242,Canada,British Columbia,Dawson Creek,U5I 4F1,Male,Bachelor,-43234,Married,Star,7597.91,2018 Promotion,2018,3,<NA>,<NA>
6560,115505,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-10605,Married,Nova,5860.17,2018 Promotion,2018,4,<NA>,<NA>
6570,430398,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-17534,Married,Nova,49423.80,2018 Promotion,2018,3,<NA>,<NA>
7373,152016,Canada,Ontario,Toronto,P1J 8T7,Female,Bachelor,-58486,Married,Aurora,5067.21,2018 Promotion,2018,2,<NA>,<NA>
8576,194065,Canada,Ontario,Sudbury,M5V 1G5,Female,Bachelor,-31911,Married,Nova,2888.85,2018 Promotion,2018,2,<NA>,<NA>
8767,212128,Canada,Ontario,Toronto,P2T 6G3,Male,Bachelor,-49001,Married,Nova,3130.68,2018 Promotion,2018,2,<NA>,<NA>
10232,790475,Canada,Ontario,Trenton,K8V 4B2,Female,Bachelor,-34079,Married,Nova,12913.50,2018 Promotion,2018,2,<NA>,<NA>
11635,366599,Canada,Ontario,Toronto,M1R 4K3,Female,Bachelor,-9081,Married,Star,6915.73,2018 Promotion,2018,4,<NA>,<NA>
12596,436087,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,-46470,Married,Star,4786.89,2018 Promotion,2018,4,2018,8
13564,364596,Canada,Quebec,Tremblant,H5Y 2S9,Female,Bachelor,-26322,Single,Aurora,16710.84,2018 Promotion,2018,4,2018,12
14327,239955,Canada,Quebec,Hull,J8Y 3Z5,Female,Bachelor,-47310,Married,Nova,6366.23,2018 Promotion,2018,3,<NA>,<NA>
14355,347013,Canada,Quebec,Quebec City,G1B 3L5,Male,Bachelor,-39503,Married,Nova,6446.71,2018 Promotion,2018,3,<NA>,<NA>
15416,729561,Canada,Quebec,Quebec City,G1B 3L5,Female,Bachelor,-19332,Divorced,Star,5308.29,2018 Promotion,2018,2,<NA>,<NA>
16431,734647,Canada,Saskatchewan,Regina,S1J 3C5,Male,Bachelor,-46303,Married,Nova,11280.73,2018 Promotion,2018,4,<NA>,<NA>
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297,Married,Star,10018.66,2018 Promotion,2018,4,<NA>,<NA>

In [36]:
# contar cuantos negativos hay
df_history.loc[df_history['salary'] < 0, 'salary'].unique()

<IntegerArray>
[-49830, -12497, -46683, -45962, -19325, -43234, -10605, -17534, -58486,
 -31911, -49001, -34079,  -9081, -46470, -26322, -47310, -39503, -19332,
 -46303, -57297]
Length: 20, dtype: Int64

In [37]:
# buscar posible patron: ver los totales de 2018 promotion
df_history[df_history['enrollment_type'] == '2018 Promotion'].shape[0]

971

In [38]:
# ver los totales de 2018 promotion que son negativos: 20 de 971. No es relevante
df_history[(df_history['enrollment_type'] == '2018 Promotion') & (df_history['salary'] < 0)].shape[0]

20

In [39]:
# ver cuantos negativos son de bachelor

df_history[(df_history['education'] == 'Bachelor') & (df_history['salary'] < 0)]

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
1894,959977,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,-12497,Married,Aurora,9453.00,2018 Promotion,2018,3,<NA>,<NA>
2471,232755,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,-46683,Single,Nova,4787.81,2018 Promotion,2018,3,<NA>,<NA>
3575,525245,Canada,British Columbia,Victoria,V10 6T5,Male,Bachelor,-45962,Married,Star,2402.33,2018 Promotion,2018,3,<NA>,<NA>
3932,603070,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,-19325,Single,Star,2893.74,2018 Promotion,2018,3,<NA>,<NA>
4712,491242,Canada,British Columbia,Dawson Creek,U5I 4F1,Male,Bachelor,-43234,Married,Star,7597.91,2018 Promotion,2018,3,<NA>,<NA>
6560,115505,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-10605,Married,Nova,5860.17,2018 Promotion,2018,4,<NA>,<NA>
6570,430398,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-17534,Married,Nova,49423.80,2018 Promotion,2018,3,<NA>,<NA>
7373,152016,Canada,Ontario,Toronto,P1J 8T7,Female,Bachelor,-58486,Married,Aurora,5067.21,2018 Promotion,2018,2,<NA>,<NA>
8576,194065,Canada,Ontario,Sudbury,M5V 1G5,Female,Bachelor,-31911,Married,Nova,2888.85,2018 Promotion,2018,2,<NA>,<NA>
8767,212128,Canada,Ontario,Toronto,P2T 6G3,Male,Bachelor,-49001,Married,Nova,3130.68,2018 Promotion,2018,2,<NA>,<NA>
10232,790475,Canada,Ontario,Trenton,K8V 4B2,Female,Bachelor,-34079,Married,Nova,12913.50,2018 Promotion,2018,2,<NA>,<NA>
11635,366599,Canada,Ontario,Toronto,M1R 4K3,Female,Bachelor,-9081,Married,Star,6915.73,2018 Promotion,2018,4,<NA>,<NA>
12596,436087,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,-46470,Married,Star,4786.89,2018 Promotion,2018,4,2018,8
13564,364596,Canada,Quebec,Tremblant,H5Y 2S9,Female,Bachelor,-26322,Single,Aurora,16710.84,2018 Promotion,2018,4,2018,12
14327,239955,Canada,Quebec,Hull,J8Y 3Z5,Female,Bachelor,-47310,Married,Nova,6366.23,2018 Promotion,2018,3,<NA>,<NA>
14355,347013,Canada,Quebec,Quebec City,G1B 3L5,Male,Bachelor,-39503,Married,Nova,6446.71,2018 Promotion,2018,3,<NA>,<NA>
15416,729561,Canada,Quebec,Quebec City,G1B 3L5,Female,Bachelor,-19332,Divorced,Star,5308.29,2018 Promotion,2018,2,<NA>,<NA>
16431,734647,Canada,Saskatchewan,Regina,S1J 3C5,Male,Bachelor,-46303,Married,Nova,11280.73,2018 Promotion,2018,4,<NA>,<NA>
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297,Married,Star,10018.66,2018 Promotion,2018,4,<NA>,<NA>

In [40]:
# ver cuantos bachelor hay. 19 de 10475: no es relevante
df_history[df_history['education'] == 'Bachelor'].shape[0]

10475

Al no haber encontrado relacion directa con otro campo, inputamos interactiveimputer como método avanzado. Aunque había cambiado el dato salary a int, ahora se queda float por utilizar interativeimputer

In [41]:
# marcar negativos como nulos
df_history.loc[df_history['salary'] < 0, 'salary'] = pd.NA

# imputar nulos con mediana calculada sobre valores válidos
# 1. Seleccionar columnas relevantes para imputar salary

cols_para_imputar = [
    "salary"]

df_imp = df_history[cols_para_imputar]

# 2. Aplicar IterativeImputer
from sklearn.experimental import enable_iterative_imputer  # necesario para sklearn <0.24
from sklearn.impute import IterativeImputer

iter_imp = IterativeImputer(random_state=42, max_iter=20)

df_imp_imputed = iter_imp.fit_transform(df_imp)

# Convertimos a DataFrame
df_imp_imputed = pd.DataFrame(df_imp_imputed, columns=cols_para_imputar)


# 3. Sustituir SOLO la columna salary en el dataframe original

df_history["salary"] = df_imp_imputed["salary"]


# 4. Comprobar resultados

print("Número de NaN en salary tras imputación:", df_history["salary"].isna().sum())
print(df_history["salary"].describe())

Número de NaN en salary tras imputación: 0
count     16737.000000
mean      79429.572642
std       29986.165418
min       15609.000000
25%       63991.000000
50%       79429.572642
75%       82940.000000
max      407228.000000
Name: salary, dtype: float64

In [42]:
# comprobacion

df_history.loc[df_history['salary'] < 0, 'salary'].unique()

array([], dtype=float64)

In [43]:
# comoprobar 
df_history.sample(15)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
9035,376630,Canada,Manitoba,Winnipeg,R6Y 4T5,Female,Bachelor,54417.000000,Single,Nova,12948.40,Standard,2014,3,2017,7
8679,526784,Canada,British Columbia,Whistler,V6T 1Y8,Male,Master,75891.000000,Divorced,Nova,10083.49,Standard,2016,7,<NA>,<NA>
15141,368122,Canada,British Columbia,Whistler,V6T 1Y8,Female,College,79429.572642,Single,Star,8555.89,Standard,2018,7,<NA>,<NA>
6784,618731,Canada,Ontario,Kingston,M9K 2P4,Female,Bachelor,86067.000000,Single,Nova,5555.83,Standard,2016,4,<NA>,<NA>
7363,939766,Canada,Ontario,Toronto,M2M 7K8,Female,Bachelor,48188.000000,Married,Nova,6793.77,Standard,2017,2,<NA>,<NA>
13792,834733,Canada,Manitoba,Winnipeg,R6Y 4T5,Female,College,79429.572642,Single,Star,5568.95,Standard,2015,6,<NA>,<NA>
13935,646359,Canada,Quebec,Tremblant,H5Y 2S9,Male,Bachelor,79989.000000,Divorced,Star,5771.61,Standard,2016,5,<NA>,<NA>
3400,151036,Canada,Quebec,Montreal,H2Y 2W2,Female,Bachelor,74521.000000,Married,Aurora,12919.42,Standard,2018,1,<NA>,<NA>
12561,805349,Canada,Ontario,Toronto,P1W 1K4,Male,Bachelor,96633.000000,Divorced,Star,4050.51,Standard,2018,6,<NA>,<NA>
15413,156673,Canada,Ontario,Toronto,P1W 1K4,Male,Bachelor,55002.000000,Married,Star,9198.69,Standard,2013,10,<NA>,<NA>
15502,647684,Canada,Ontario,Thunder Bay,K8T 5M5,Male,Master,125880.000000,Divorced,Star,9594.25,Standard,2015,11,<NA>,<NA>
8703,577844,Canada,British Columbia,Vancouver,V6E 3D9,Female,College,79429.572642,Single,Nova,10196.11,Standard,2014,3,<NA>,<NA>
7076,185509,Canada,Quebec,Tremblant,H5Y 2S9,Female,Bachelor,80816.000000,Single,Nova,5989.77,Standard,2015,8,<NA>,<NA>
16336,276650,Canada,British Columbia,Kelowna,V09 2E9,Male,College,79429.572642,Single,Star,19116.57,Standard,2014,6,<NA>,<NA>
14174,621876,Canada,New Brunswick,Fredericton,E3B 2H2,Male,Bachelor,61670.000000,Married,Star,6289.80,Standard,2012,11,<NA>,<NA>

In [44]:
df_history.isnull().sum()

loyalty_number            0
country                   0
province                  0
city                      0
postal_code               0
gender                    0
education                 0
salary                    0
marital_status            0
loyalty_card              0
clv                       0
enrollment_type           0
enrollment_year           0
enrollment_month          0
cancellation_year     14670
cancellation_month    14670
dtype: int64

In [45]:
columnas = ['cancellation_year', 'cancellation_month']
porcentaje_nulos = df_history[columnas].isna().mean() * 100
print(porcentaje_nulos)

cancellation_year     87.650117
cancellation_month    87.650117
dtype: float64

estos nulos no son nulos de verdad, son clientes que siguen en activo. las casillas están como nulas porque no hay regstros de cancelación.

In [46]:
# añadir columna is_active para poder utilizarlo en cálculos cuantitativos o filtrado. 0 es false y 1 es true

# 1. Normalizar nombres (quitar espacios)
df_history.columns = df_history.columns.str.strip()

# 2. Asegurar cancellation_year como numérico nullable
df_history['cancellation_year'] = pd.to_numeric(df_history['cancellation_year'], errors='coerce').astype('Int64')

# 3. Crear is_active: 1 = activo (no hay año de cancelación), 0 = cancelado
df_history['is_active'] = df_history['cancellation_year'].isna().astype('Int64')

# 4. Comprobaciones rápidas sobre is_active
print("is_active dtype:", df_history['is_active'].dtype)
print(df_history['is_active'].value_counts(dropna=False))

is_active dtype: Int64
is_active
1    14670
0     2067
Name: count, dtype: Int64

In [47]:
df_history.sample(10)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,is_active
15458,822765,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,79429.572642,Single,Star,9392.56,Standard,2016,4,<NA>,<NA>,1
12881,444092,Canada,British Columbia,Vancouver,V1E 4R6,Female,College,79429.572642,Single,Star,4558.50,Standard,2016,6,<NA>,<NA>,1
4313,286975,Canada,Ontario,Toronto,M2P 4F6,Female,Bachelor,58988.000000,Single,Nova,2806.70,Standard,2013,12,<NA>,<NA>,1
16467,571406,Canada,Nova Scotia,Halifax,B3J 9S2,Male,Master,113785.000000,Married,Star,22658.54,Standard,2013,7,2014,3,0
15923,599778,Canada,Quebec,Tremblant,H5Y 2S9,Female,Bachelor,44642.000000,Single,Star,17646.73,2018 Promotion,2018,3,<NA>,<NA>,1
238,717700,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,62093.000000,Married,Star,4315.79,Standard,2015,9,<NA>,<NA>,1
12981,340691,Canada,Quebec,Montreal,H2T 9K8,Male,College,79429.572642,Single,Star,4713.40,Standard,2015,12,<NA>,<NA>,1
11994,682571,Canada,British Columbia,Kelowna,V09 2E9,Female,Bachelor,56594.000000,Divorced,Star,2899.32,Standard,2012,12,<NA>,<NA>,1
15,205785,Canada,Ontario,Toronto,M2M 6J7,Male,Master,128118.000000,Married,Star,3873.65,Standard,2016,8,<NA>,<NA>,1
12752,700731,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,60390.000000,Divorced,Star,4363.60,Standard,2017,4,2017,12,0

In [48]:
columnas = ['cancellation_year', 'cancellation_month']

# 1. Convertir a object y reemplazar NaN por "Activo"
for col in columnas:
    df_history[col] = df_history[col].astype('object').fillna('Activo')

# 2. Comprobar resultados
print(df_history[columnas].dtypes)  # deberían salir como object
print(df_history[columnas].head(10))

cancellation_year     object
cancellation_month    object
dtype: object
  cancellation_year cancellation_month
0            Activo             Activo
1            Activo             Activo
2              2018                  1
3            Activo             Activo
4            Activo             Activo
5            Activo             Activo
6            Activo             Activo
7            Activo             Activo
8            Activo             Activo
9            Activo             Activo

In [49]:
df_history.sample(10)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,is_active
5542,283290,Canada,Alberta,Peace River,T9O 2W2,Female,Bachelor,49175.000000,Single,Nova,3971.35,Standard,2015,1,Activo,Activo,1
3656,488044,Canada,Ontario,Toronto,P1W 1K4,Male,College,79429.572642,Single,Aurora,15994.01,Standard,2016,9,Activo,Activo,1
8144,113040,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,65935.000000,Divorced,Nova,8427.17,Standard,2013,1,Activo,Activo,1
11230,813520,Canada,British Columbia,Dawson Creek,U5I 4F1,Male,College,79429.572642,Married,Star,2593.40,Standard,2012,9,Activo,Activo,1
10333,405804,Canada,Manitoba,Winnipeg,R2C 0M5,Male,Master,109361.000000,Divorced,Star,2397.04,Standard,2015,10,Activo,Activo,1
9626,170982,Canada,Quebec,Montreal,H2Y 4R4,Male,High School or Below,47587.000000,Divorced,Nova,24127.50,Standard,2018,12,Activo,Activo,1
1692,583165,Canada,Quebec,Montreal,H2T 9K8,Male,Bachelor,96786.000000,Married,Aurora,6382.05,Standard,2013,5,2013,12,0
6548,487359,Canada,New Brunswick,Fredericton,E3B 2H2,Female,Bachelor,46738.000000,Married,Nova,5301.84,Standard,2017,5,Activo,Activo,1
390,685792,Canada,British Columbia,Vancouver,V6E 3D9,Female,Bachelor,60582.000000,Divorced,Star,4563.02,Standard,2016,7,2017,9,0
10023,608974,Canada,Alberta,Banff,T4V 1D4,Female,Master,117771.000000,Single,Star,2248.45,Standard,2012,10,Activo,Activo,1

In [50]:
df_history.isnull().sum()

loyalty_number        0
country               0
province              0
city                  0
postal_code           0
gender                0
education             0
salary                0
marital_status        0
loyalty_card          0
clv                   0
enrollment_type       0
enrollment_year       0
enrollment_month      0
cancellation_year     0
cancellation_month    0
is_active             0
dtype: int64

In [51]:
# Une los dos conjuntos de datos de la forma más eficiente

# 1. guaedar cada uno limpio

df_history.to_csv("df_history_clean.csv", index=False)
df_activity.to_csv("df_activity_clean.csv", index=False)

In [52]:
# 2. juntar en un documento unico

# Cargar los CSV limpios
df1 = pd.read_csv('df_history_clean.csv')  
df2 = pd.read_csv('df_activity_clean.csv')  

# Asegurar que la columna para merge tenga el mismo nombre y tipo
df1['loyalty_number'] = df1['loyalty_number'].astype(str)
df2['loyalty_number'] = df2['loyalty_number'].astype(str)

# Merge por 'loyalty_number'
df_combined = pd.merge(df1, df2, on='loyalty_number', how='outer')

# Verificar el resultado
print(df_combined.info())
print(df_combined.head(10))

# Guardar CSV combinado
df_combined.to_csv('documentos_unidos.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403760 entries, 0 to 403759
Data columns (total 26 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loyalty_number               403760 non-null  object
 1   country                      403760 non-null  object
 2   province                     403760 non-null  object
 3   city                         403760 non-null  object
 4   postal_code                  403760 non-null  object
 5   gender                       403760 non-null  object
 6   education                    403760 non-null  object
 7   salary                       403760 non-null  float64
 8   marital_status               403760 non-null  object
 9   loyalty_card                 403760 non-null  object
 10  clv                          403760 non-null  float64
 11  enrollment_type              403760 non-null  object
 12  enrollment_year              403760 non-null  int64
 13  enrollment_month             403760 non-null  int64
 14  cancellation_year            403760 non-null  object
 15  cancellation_month           403760 non-null  object
 16  is_active                    403760 non-null  int64
 17  year                         403760 non-null  int64
 18  month                        403760 non-null  int64
 19  flights_booked               403760 non-null  int64
 20  flights_with_companions      403760 non-null  int64
 21  total_flights                403760 non-null  int64
 22  distance                     403760 non-null  int64
 23  points_accumulated           403760 non-null  float64
 24  points_redeemed              403760 non-null  float64
 25  dollar_cost_points_redeemed  403760 non-null  int64
dtypes: float64(4), int64(10), object(12)
memory usage: 80.1+ MB
None
  loyalty_number country province      city postal_code  gender education  \
0         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
1         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
2         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
3         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
4         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
5         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
6         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
7         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
8         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor
9         100018  Canada  Alberta  Edmonton     T9G 1W3  Female  Bachelor

    salary marital_status loyalty_card     clv enrollment_type  \
0  92552.0        Married       Aurora  7919.2        Standard
1  92552.0        Married       Aurora  7919.2        Standard
2  92552.0        Married       Aurora  7919.2        Standard
3  92552.0        Married       Aurora  7919.2        Standard
4  92552.0        Married       Aurora  7919.2        Standard
5  92552.0        Married       Aurora  7919.2        Standard
6  92552.0        Married       Aurora  7919.2        Standard
7  92552.0        Married       Aurora  7919.2        Standard
8  92552.0        Married       Aurora  7919.2        Standard
9  92552.0        Married       Aurora  7919.2        Standard

   enrollment_year  enrollment_month cancellation_year cancellation_month  \
0             2016                 8            Activo             Activo
1             2016                 8            Activo             Activo
2             2016                 8            Activo             Activo
3             2016                 8            Activo             Activo
4             2016                 8            Activo             Activo
5             2016                 8            Activo             Activo
6             2016                 8            Activo             Activo
7             2016                 8            Activo             Activo
8             2016                 8            Activo             Activo
9             2016                 8            Activo             Activo

   is_active  year  month  flights_booked  flights_with_companions  \
0          1  2017      1               3                        0
1          1  2017      2               2                        2
2          1  2018     10               6                        4
3          1  2017      4               4                        0
4          1  2017      5               0                        0
5          1  2017      6               4                        1
6          1  2017      7              10                        0
7          1  2017      9               9                        4
8          1  2017      8              10                        5
9          1  2017     10               6                        0

   total_flights  distance  points_accumulated  points_redeemed  \
0              3      1521               152.0              0.0
1              4      1320               132.0              0.0
2             10      3110               311.0            385.0
3              4       924                92.0              0.0
4              0         0                 0.0              0.0
5              5      4330               433.0              0.0
6             10      3870               387.0              0.0
7             13      1651               165.0              0.0
8             15      4200               420.0            690.0
9              6      1032               103.0              0.0

   dollar_cost_points_redeemed
0                            0
1                            0
2                           31
3                            0
4                            0
5                            0
6                            0
7                            0
8                           56
9                            0

In [53]:
df_combined.head(10)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,is_active,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,1,3,0,3,1521,152.0,0.0,0
1,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,2,2,2,4,1320,132.0,0.0,0
2,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2018,10,6,4,10,3110,311.0,385.0,31
3,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,4,4,0,4,924,92.0,0.0,0
4,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,5,0,0,0,0,0.0,0.0,0
5,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,6,4,1,5,4330,433.0,0.0,0
6,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,7,10,0,10,3870,387.0,0.0,0
7,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,9,9,4,13,1651,165.0,0.0,0
8,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,8,10,5,15,4200,420.0,690.0,56
9,100018,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.2,Standard,2016,8,Activo,Activo,1,2017,10,6,0,6,1032,103.0,0.0,0